// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Persistence.Context;

#nullable disable

namespace TaxCalculator.Persistence.Migrations
{
    [DbContext(typeof(TaxCalculationContext))]
    partial class TaxCalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tax")
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.Domain.Entities.TaxBandType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxRange")
                        .HasColumnType("int");

                    b.Property<int>("MinRange")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBandTypes", "tax");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 3, 9, 51, 26, 276, DateTimeKind.Utc).AddTicks(9190),
                            MaxRange = 5000,
                            MinRange = 0,
                            Name = "Tax Band A",
                            TaxRate = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 3, 3, 9, 51, 26, 276, DateTimeKind.Utc).AddTicks(9222),
                            MaxRange = 20000,
                            MinRange = 5000,
                            Name = "Tax Band B",
                            TaxRate = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 3, 3, 9, 51, 26, 276, DateTimeKind.Utc).AddTicks(9225),
                            MaxRange = 2147483647,
                            MinRange = 20000,
                            Name = "Tax Band C",
                            TaxRate = 40
                        });
                });

            modelBuilder.Entity("TaxCalculator.Domain.Entities.TaxCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AnnualTaxPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("GrossAnnualSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("GrossMonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("MonthlyTaxPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("NetAnnualSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("NetMonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("Id");

                    b.ToTable("TaxCalculations", "tax");
                });
#pragma warning restore 612, 618
        }
    }
}
